#information for application name and launcher
Application:

  name: Python VA
  menuname: Python VA
  asciibanner: tools/deploy-scripts/assets/asciibanner-VA.txt
  icon: icons/virtualactuary.ico
  installdir: '%localappdata%\PythonVA'

  #After installation
  pause: 1

  # map "from/path/" -> "to/path"
  programdata:
    - [ ./bin, ./bin]
    - [ ./src, ./src]
    - [ ./scripts, ./scripts]

    # These are neccessary for the uninstallation script
    - [ ./tools/deploy-scripts/tools/remove-and-kill-directory.py, ./tools/deploy-scripts/tools/remove-and-kill-directory.py]
    - [ ./tools/deploy-scripts/includes/rm_and_kill.py, ./tools/deploy-scripts/includes/rm_and_kill.py]

    - [./Add xlwings to Excel.exe,       ./Add xlwings to Excel.exe]
    - [./Create new xlwings project.exe, ./Create new xlwings project.exe]
    - [./Python VA cmd.exe,              ./Python VA cmd.exe]
    - [./python.exe,                     ./python.exe]
    - [./Remove xlwings from Excel.exe,  ./Remove xlwings from Excel.exe]
    - [./Spyder VA.exe,                  ./Spyder VA.exe]
    - [./pip.exe,                        ./pip.exe]
    - [./resources,                      ./resources]

  startmenu:
    - 'Add xlwings to Excel.exe'
    - 'Create new xlwings project.exe'
    - 'Python VA cmd.exe'
    - 'python.exe'
    - 'Remove xlwings from Excel.exe'
    - 'Spyder VA.exe'


#Download Python/R (optional) and their dependencies to be deployed
Dependencies:
  deploy-scripts: 15f91fe
  python:
    - numpy==1.19.3
    - locate==0.0.1
    - openpyxl~=3.0
    - pandas~=1.1
    - scipy
    - ipython
    - jupyter
    - xlwings
    - spyder
